<?php

/**
 * @file
 * Main module file.
 */
define('WAH_TABLE_NAME', 'webform_access_history');
define('WAH_DEFAULT_HIGHLIGHT_CSS', 'border-left: 6px solid lightblue;');
define('WAH_DEFAULT_ALLOWED_PATHS', 'results/%,node/%/webform-results');


/**
 * Implements hook_menu().
 */
function webform_access_history_menu()
{

    // settings page
    $items['webform/access/history/settings'] = array(
        'title' => 'Webform Access History - Settings',
        'page callback'=>array('drupal_get_form'),
        'page arguments' => array('webform_access_history_options'),
        'access arguments' => array('wah admin module'),
        'type' => MENU_CALLBACK,
        'file' => 'webform_access_history.admin.inc',
    );


    return $items;
}


/*
 * Permissions
 * */
function webform_access_history_permission()
{
    return array(
        'wah see submission viewing list' => array(
            'title' => t('See who has looked at webform submissions'),
            'description' => t('Who is allowed to see submissions look up activity'),
        ),
        'wah reset table' => array(
            'title' => t('Reset table history'),
            'description' => t('Clears table. Almost like uninstalling and re-installing module'),
        ),
        'wah admin module' => array(
            'title' => t('Administer this module'),
            'description' => t('Module administration settings '),
        ),
    );
}

/**
 * Records when someone has looked at a submissions. Triggers off hook_webform_submission_load(). This is the
 * other work horse of this function. It *records* each time a logged in user looks at a submission.
 *
 * @param $submissions
 */
function webform_access_history_webform_submission_load(&$submissions)
{

    // only react on node/%/submission/% Paths
    preg_match('#node/\d+/submission/\d+#', current_path(), $result);

    // If count is less than one, just return. Don't
    // do anything more.
    if (count($result) < 1) {
        // dpm('not counting');
        return;
    }

    // get a copy of the user object
    $whoami = $GLOBALS['user'];

    // record submission view
    foreach ($submissions as $sub) {
        db_insert(WAH_TABLE_NAME)
            ->fields(array(
                'logged_in_uid' => $whoami->uid,
                'submitted_uid' => $sub->uid,
                'sid' => $sub->sid,
                'nid' => $sub->nid,
                'timestamp' => time(),
            ))
            ->execute();
    }


}


/**
 * Implements hook_block_info().
 */
function webform_access_history_block_info()
{
    // Main block that inserts JavaScript logic to highlight
    // unseen submissions
    $blocks['webform_access_history_jsblock'] = array(
        'info' => t('Webform Access Hisotry, Add Info to Javascript (Main Block)'),
        'cache' => DRUPAL_NO_CACHE
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function webform_access_history_block_view($delta = '')
{
    module_load_include('inc', 'webform_access_history', 'webform_access_history.report');

    // This example is adapted from node.module.
    $block = array();

    switch ($delta) {

        case 'webform_access_history_jsblock':
            $block = array(
                'subject' => t('<none>'),
                'content' => webform_access_history_jsObject()
            );

    }
    return $block;
}


/**
 * Implements hook_install()
 */
function webform_access_history_install()
{
    _webform_access_history_firstrun();
}

/**
 * Implements hook_uninstall()
 */
function webform_access_history_uninstall()
{
    db_drop_table(WAH_TABLE_NAME);
}

/**
 * Helper function that creates the database if it does not exists.
 */
function _webform_access_history_firstrun()
{

    // If the table doesn't exist, create it.
    if (!db_table_exists(WAH_TABLE_NAME)) {


        // build schema
        $schema = array(
            'description' => 'Record of who looked at what',
            'fields' => array(
                'logged_in_uid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
                'submitted_uid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
                'sid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
                'nid' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE),
                'timestamp' => array('type' => 'int', 'unsigned' => TRUE, 'not null' => TRUE, 'default' => '0'),
            ),
        );

        // create table
        db_create_table(WAH_TABLE_NAME, $schema);
    }

}


function _webform_access_history_enforce_permission()
{
    // enforce permission!
    return user_access('wah see submission viewing list');
}